name: pull request build workflow

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        # bring in all history because the gradle versions plugin needs to "walk back" to the closest ancestor tag
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
        # add --info or --debug below for more details when trying to understand issues
      run: ./gradlew clean build --stacktrace --no-daemon
